### ISSUE TITLE
Facing error in run.sh

### ISSUE THREAD

**Issue by ak53** [jimbozhang/kaldi-gop#32]
I'm facing this error:
(base) Amandeeps-MacBook-Air:gop-compute aman$ ./run.sh
local/compute-gmm-gop.sh --nj 1 --cmd run.pl data/eval data/lang exp/tri1 exp/eval_gop
local/compute-gmm-gop.sh: feature type is delta
local/compute-gmm-gop.sh: computing GOP in data/eval using model from exp/tri1, putting results in exp/eval_gop
bash: line 1:  1216 Abort trap: 6           ( compute-gmm-gop exp/eval_gop/tree exp/eval_gop/final.mdl data/lang/L.fst "ark,s,cs:apply-cmvn  --utt2spk=ark:data/eval/split1/1/utt2spk scp:data/eval/split1/1/cmvn.scp scp:data/eval/split1/1/feats.scp ark:- | add-deltas  ark:- ark:- |" "ark:utils/sym2int.pl --map-oov 221 -f 2- data/lang/words.txt data/eval/split1/1/text|" ark,t:exp/eval_gop/gop.1 ) 2>> exp/eval_gop/log/gop.1.log >> exp/eval_gop/log/gop.1.log
run.pl: job failed, log is in exp/eval_gop/log/gop.1.log

**Comment by ak53** [comment]
The issue was the absence of the files apply-cmvn and add-delta, solved by pasting the executable files from kaldi-master/src/featbin(full kaldi repo) to the build folder.

**Comment by amandeepbaberwal** [comment]
@ak53 hi amandeep, amandeep here, i am getting the same issue, and i did the same thing as you did but still getting same error. Any ideas?
